language: python

# Python versions
python:
  - "2.6"
  - "2.7"
  - "3.3"

addons:
  sauce_connect:
    username: "barseghyanartur"
    access_key:
      secure: "KLqwKfkoCmGzLj48Kn5o2lBKURhrsClfL+0pikrhzhsoNI9u8+jsK+XoqEXyex6+EYiLvihO0cktFe456fOkxhFTE7dTd+NAstWe3RQp0A5fp5BAex1sWxnEvWzWMDdD+u5AfWBxW2Jbn5oIMmJd9fc0rD0sHwFHLGP7kOiMI/0="

# Environments
env:
  - DJANGO15=true
  - DJANGO16=true

# Command to install dependencies
install:
  - pip install -r examples/requirements.txt
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' && $DJANGO15 == true ]]; then pip uninstall Django -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' && $DJANGO15 == true ]]; then pip install Django==1.5.5; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' && $DJANGO16 == true ]]; then pip uninstall Django -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' && $DJANGO16 == true ]]; then pip install Django==1.6; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DJANGO15 == true ]]; then pip uninstall Django -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DJANGO15 == true ]]; then pip install Django==1.5.5; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DJANGO16 == true ]]; then pip uninstall Django -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DJANGO16 == true ]]; then pip install Django==1.6; fi
  #- if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip uninstall django-localeurl -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install -r examples/requirements3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $DJANGO15 == true ]]; then pip uninstall Django -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $DJANGO15 == true ]]; then pip install Django==1.5.5; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $DJANGO16 == true ]]; then pip uninstall Django -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $DJANGO16 == true ]]; then pip install Django==1.6; fi
  - mkdir examples/logs
  - mkdir examples/media
  - mkdir examples/media/static
  - python examples/example/manage.py syncdb --noinput 
# --noinput --traceback -v 3
# Command to run tests
script: 
  - python examples/example/manage.py test dash
# --traceback -v 3

